import React, { useEffect, useMemo, useState } from 'react'
import ShoppingAssistant from './ShoppingAssistant'
import NutritionCard from './NutritionCard'

const API = 'https://www.themealdb.com/api/json/v1/1'
const SHOPPING_KEY = 'cooktonight-shopping-list'
const FAVORITES_KEY = 'cooktonight-favorites'
const aliases = { tomatoes: 'tomato', potatoes: 'potato', onions: 'onion', chillies: 'chili', chilies: 'chili', chilli: 'chili', 'green chilli': 'green chili', 'green chilies': 'green chili', aloo: 'potato', tamatar: 'tomato', pyaaz: 'onion', pyaz: 'onion', dahi: 'yogurt', adrak: 'ginger', lehsan: 'garlic' }
const groups = { chicken: ['chicken', 'chicken breast', 'chicken thigh', 'chicken wings'], rice: ['rice', 'basmati rice', 'brown rice'], potato: ['potato', 'sweet potato'], onion: ['onion', 'red onion', 'shallot'], tomato: ['tomato', 'tomato paste', 'canned tomato'], garlic: ['garlic', 'garlic paste', 'minced garlic'], ginger: ['ginger', 'ginger paste'], yogurt: ['yogurt', 'greek yogurt', 'curd'], chili: ['chili', 'green chili', 'red chili'], egg: ['egg', 'eggs'], milk: ['milk'], flour: ['flour', 'plain flour'], lentil: ['lentil', 'lentils', 'dal'], bread: ['bread'] }
const prices = { chicken: 520, rice: 260, potato: 100, onion: 90, tomato: 120, garlic: 80, ginger: 70, yogurt: 180, chili: 70, egg: 90, milk: 220, flour: 140, lentil: 280, bread: 160 }
const meat = ['chicken', 'beef', 'pork', 'lamb', 'mutton', 'goat', 'turkey', 'duck', 'ham', 'bacon', 'sausage', 'fish', 'salmon', 'tuna', 'prawn', 'shrimp', 'anchovy', 'crab', 'lobster']
const normalize = value => { const text = String(value || '').toLowerCase().trim().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' '); return aliases[text] || text.replace(/s$/, '') }
const canonical = value => { const text = normalize(value); for (const [key, values] of Object.entries(groups)) if (values.some(item => normalize(item) === text || text.includes(normalize(item)) || normalize(item).includes(text))) return key; return text }
const ingredientsOf = meal => Array.from({ length: 20 }, (_, i) => ({ name: meal[`strIngredient${i + 1}`]?.trim(), measure: meal[`strMeasure${i + 1}`]?.trim() })).filter(item => item.name).map(item => ({ ...item, key: canonical(item.name) }))
const cleanInstructions = text => String(text || '').replace(/\r\n?/g, '\n').replace(/<br\s*\/?>/gi, '\n').replace(/<\/p>/gi, '\n').replace(/&nbsp;/gi, ' ').replace(/&amp;/gi, '&').replace(/&quot;/gi, '"').replace(/&#39;/gi, "'").trim()
const instructionsOf = text => { const value = cleanInstructions(text); if (!value) return []; const lines = value.split(/\n+/).map(item => item.replace(/^\s*(?:step\s*)?\d+\s*[.):-]?\s*/i, '').trim()).filter(Boolean); if (lines.length > 1) return lines; const sentences = value.split(/(?<=[.!?])\s+/).map(item => item.trim()).filter(Boolean); return sentences.length > 1 ? sentences : [value] }
const estimatedIngredientCost = (item, people) => Math.max(35, Math.round((prices[item.key] || 95) * Math.max(1, people / 4)))
const estimatedMinutes = meal => { const ingredients = ingredientsOf(meal).length; const steps = instructionsOf(meal.strInstructions).length; const category = String(meal.strCategory || '').toLowerCase(); let minutes = 10 + ingredients * 2 + steps * 4; if (category.includes('dessert') || category.includes('baking')) minutes += 15; if (category.includes('stew') || category.includes('soup')) minutes += 15; if (category.includes('pasta') || category.includes('rice')) minutes += 5; return Math.min(120, Math.max(15, Math.round(minutes / 5) * 5)) }
const scoreOf = (meal, available, budget, people) => { const have = available.map(canonical); const items = ingredientsOf(meal); const unique = [...new Set(items.map(item => item.key))]; const matched = items.filter(item => have.includes(item.key)); const missing = items.filter(item => !have.includes(item.key)); const ingredientScore = unique.length ? matched.filter(item => unique.includes(item.key)).length / unique.length : 0; const shoppingCost = missing.reduce((sum, item) => sum + estimatedIngredientCost(item, people), 0); const budgetScore = budget >= shoppingCost ? 1 : budget / Math.max(shoppingCost, 1); const score = Math.max(0, Math.min(100, Math.round(ingredientScore * 75 + budgetScore * 25))); const text = items.map(item => item.name).join(' ').toLowerCase(); return { ...meal, items, matched, missing, ingredientScore: Math.round(ingredientScore * 100), score, shoppingCost, totalCost: shoppingCost + matched.reduce((sum, item) => sum + estimatedIngredientCost(item, people), 0), overBudget: shoppingCost > budget, vegetarian: !meat.some(word => text.includes(word)), minutes: estimatedMinutes(meal), steps: instructionsOf(meal.strInstructions) } }
async function fetchJson(url) { const response = await fetch(url); if (!response.ok) throw new Error(`Recipe service returned ${response.status}`); return response.json() }
async function getMeals(ingredients) { const names = ingredients.map(normalize).filter(Boolean).slice(0, 6); const candidates = new Map(); const responses = await Promise.allSettled(names.map(name => fetchJson(`${API}/filter.php?i=${encodeURIComponent(name)}`))); responses.forEach(result => { if (result.status === 'fulfilled') (result.value.meals || []).forEach(meal => candidates.set(meal.idMeal, meal)) }); const ids = [...candidates.values()].slice(0, 40); const details = await Promise.allSettled(ids.map(meal => fetchJson(`${API}/lookup.php?i=${meal.idMeal}`))); return details.filter(result => result.status === 'fulfilled').map(result => result.value.meals?.[0]).filter(Boolean) }
function App() {
  const [people, setPeople] = useState(4)
  const [budget, setBudget] = useState(2000)
  const [ingredients, setIngredients] = useState(['Chicken', 'Rice', 'Potatoes', 'Onion', 'Tomatoes'])
  const [input, setInput] = useState('')
  const [meals, setMeals] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [visibleCount, setVisibleCount] = useState(6)
  const [recipe, setRecipe] = useState(null)
  const [preference, setPreference] = useState('all')
  const [timeLimit, setTimeLimit] = useState('all')
  const [sortBy, setSortBy] = useState('match')
  const [favorites, setFavorites] = useState(() => { try { return JSON.parse(localStorage.getItem(FAVORITES_KEY) || '[]') } catch { return [] } })
  const [favoritesOpen, setFavoritesOpen] = useState(false)
  const [surpriseOpen, setSurpriseOpen] = useState(false)
  const [shoppingItems, setShoppingItems] = useState(() => { try { return JSON.parse(localStorage.getItem(SHOPPING_KEY) || '[]') } catch { return [] } })
  const [shoppingOpen, setShoppingOpen] = useState(false)
  useEffect(() => { localStorage.setItem(SHOPPING_KEY, JSON.stringify(shoppingItems)) }, [shoppingItems])
  useEffect(() => { localStorage.setItem(FAVORITES_KEY, JSON.stringify(favorites)) }, [favorites])
  useEffect(() => { let active = true; setLoading(true); setError(''); getMeals(ingredients).then(data => { if (!active) return; setMeals(data); setVisibleCount(6); setLoading(false); if (!data.length) setError('No recipes found. Try adding another ingredient.') }).catch(error => { if (!active) return; setMeals([]); setError(error.message || 'Unable to load recipes right now.'); setLoading(false) }); return () => { active = false } }, [ingredients])
  const scoredResults = useMemo(() => meals.map(meal => scoreOf(meal, ingredients, budget, people)), [meals, ingredients, budget, people])
  const results = useMemo(() => { let filtered = scoredResults; if (preference === 'vegetarian') filtered = filtered.filter(meal => meal.vegetarian); if (preference === 'budget') filtered = filtered.filter(meal => !meal.overBudget); if (timeLimit !== 'all') filtered = filtered.filter(meal => meal.minutes <= Number(timeLimit)); return [...filtered].sort((a, b) => { if (sortBy === 'cost') return a.shoppingCost - b.shoppingCost || b.score - a.score; if (sortBy === 'ingredients') return b.ingredientScore - a.ingredientScore || b.score - a.score; if (sortBy === 'time') return a.minutes - b.minutes || b.score - a.score; return b.score - a.score }) }, [scoredResults, preference, timeLimit, sortBy])
  const best = results[0]
  const surpriseMeal = useMemo(() => { if (!results.length) return null; const pool = results.slice(0, Math.min(results.length, 12)); return pool[Math.floor(Math.random() * pool.length)] }, [results, surpriseOpen])
  const favoriteIds = useMemo(() => new Set(favorites.map(item => item.idMeal)), [favorites])
  const addIngredient = value => { const clean = value.trim(); if (!clean || ingredients.some(item => canonical(item) === canonical(clean))) return; setIngredients(items => [...items, clean]); setInput('') }
  const toggleFavorite = meal => { setFavorites(current => current.some(item => item.idMeal === meal.idMeal) ? current.filter(item => item.idMeal !== meal.idMeal) : [...current, { ...meal }] ) }
  const addMissing = meal => { setShoppingItems(current => { const next = [...current]; meal.missing.forEach(item => { const id = `${canonical(item.name)}-${item.measure || ''}`; if (!next.some(existing => existing.id === id)) next.push({ id, name: item.name, measure: item.measure, price: estimatedIngredientCost(item, people), purchased: false }) }); return next }); setShoppingOpen(true) }
  const visibleMeals = results.slice(1, visibleCount + 1)
  const favoriteMeals = favorites.map(item => scoreOf(item, ingredients, budget, people))
  const canShowMore = visibleCount < results.length - 1
  const resetFilters = () => { setPreference('all'); setTimeLimit('all'); setVisibleCount(6) }
  const setTime = value => { setTimeLimit(value); setVisibleCount(6) }
  const setSort = value => { setSortBy(value); setVisibleCount(6) }
  const openFavorite = meal => { setRecipe(meal); setFavoritesOpen(false) }
  const alternativeMeals = useMemo(() => { if (!recipe) return []; return scoredResults.filter(meal => meal.idMeal !== recipe.idMeal).map(meal => ({ ...meal, alternativeType: meal.shoppingCost < recipe.shoppingCost ? 'Cheaper' : meal.minutes < recipe.minutes ? 'Faster' : meal.ingredientScore > recipe.ingredientScore ? 'Better match' : meal.vegetarian && !recipe.vegetarian ? 'Vegetarian' : 'Alternative' })).sort((a, b) => { const rank = { 'Cheaper': 0, 'Faster': 1, 'Better match': 2, 'Vegetarian': 3, 'Alternative': 4 }; return (rank[a.alternativeType] ?? 5) - (rank[b.alternativeType] ?? 5) || b.score - a.score }).slice(0, 4) }, [recipe, scoredResults])
  const surprise = () => { if (!results.length) return; setSurpriseOpen(true) }
  return <main className="app">
    <nav className="nav"><div className="brand">🍳 CookTonight</div><div className="nav-link">Your ingredients · Your budget · Your meal</div><div className="nav-actions"><button className="surprise-button" onClick={surprise}>🎲 Surprise Me</button><button className="favorites-button" onClick={() => setFavoritesOpen(true)}>♥ Saved {favorites.length > 0 && <b>{favorites.length}</b>}</button><button className="shopping-button" onClick={() => setShoppingOpen(true)}>🛒 Shopping {shoppingItems.filter(item => !item.purchased).length > 0 && <b>{shoppingItems.filter(item => !item.purchased).length}</b>}</button></div></nav>
    <section className="hero"><div><span className="eyebrow">LESS THINKING · BETTER MEALS</span><h1>What should I<br /><em>cook tonight?</em></h1><p>Tell us what you have, how many people you're feeding and what you can spend. We'll find meals that make sense.</p></div><div className="pan">🍳</div></section>
    <section className="planner"><div className="input-card"><label>PEOPLE</label><div className="number-input"><button onClick={() => setPeople(value => Math.max(1, value - 1))}>−</button><strong>{people}</strong><button onClick={() => setPeople(value => value + 1)}>+</button></div></div><div className="input-card"><label>BUDGET</label><div className="budget-input"><span>Rs.</span><input type="number" min="0" value={budget} onChange={event => setBudget(Math.max(0, Number(event.target.value) || 0))} /></div></div><div className="input-card ingredients-card"><label>WHAT DO YOU HAVE?</label><div className="chips">{ingredients.map(item => <button className="chip" key={item} onClick={() => setIngredients(current => current.filter(value => value !== item))}>{item} ×</button>)}<input value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => event.key === 'Enter' && addIngredient(input)} placeholder="Add ingredient…" /></div></div></section>
    <div className="filters"><span>SHOW ME</span><button className={preference === 'all' ? 'active' : ''} onClick={resetFilters}>All matches</button><button className={preference === 'budget' ? 'active' : ''} onClick={() => { setPreference('budget'); setVisibleCount(6) }}>Under my budget</button><button className={preference === 'vegetarian' ? 'active' : ''} onClick={() => { setPreference('vegetarian'); setVisibleCount(6) }}>Vegetarian</button><span className="sort-label">TIME</span><button className={timeLimit === '15' ? 'active' : ''} onClick={() => setTime('15')}>≤15 min</button><button className={timeLimit === '30' ? 'active' : ''} onClick={() => setTime('30')}>≤30 min</button><button className={timeLimit === '45' ? 'active' : ''} onClick={() => setTime('45')}>≤45 min</button><button className={timeLimit === '60' ? 'active' : ''} onClick={() => setTime('60')}>≤1 hour</button><button className={timeLimit === 'all' ? 'active' : ''} onClick={() => setTime('all')}>Any time</button><span className="sort-label">SORT</span><button className={sortBy === 'match' ? 'active' : ''} onClick={() => setSort('match')}>Best match</button><button className={sortBy === 'cost' ? 'active' : ''} onClick={() => setSort('cost')}>Lowest cost</button><button className={sortBy === 'ingredients' ? 'active' : ''} onClick={() => setSort('ingredients')}>Most ingredients</button><button className={sortBy === 'time' ? 'active' : ''} onClick={() => setSort('time')}>Quickest</button></div>
    <section className="results"><div className="section-heading"><div><span className="eyebrow">SMART MATCHING</span><h2>Meals that make sense</h2></div><span className="result-count">{results.length} meals found</span></div>
      {loading && <div className="loading-card"><div className="loader" />Finding meals…</div>}
      {!loading && error && <div className="error-card">{error}<button className="secondary" onClick={() => setIngredients(items => [...items])}>Try again</button></div>}
      {!loading && !error && !best && <div className="error-card">No meals match these filters. Try <button className="secondary" onClick={resetFilters}>Reset filters</button> or add another ingredient.</div>}
      {!loading && best && <><article className="best-card"><div className="dish-image"><img src={best.strMealThumb} alt={best.strMeal} /></div><div className="best-info"><span className="match">{best.score}% MATCH · {best.ingredientScore}% INGREDIENTS</span><h3>{best.strMeal}</h3><p>{best.strArea || 'International'} cuisine · {best.minutes} min · planned for {people} people</p><div className="ingredient-row">{best.matched.slice(0, 7).map(item => <span className="have" key={`${item.name}-${item.measure}`}>✓ {item.name}</span>)}</div>{best.missing.length > 0 && <div className="missing">Need to buy: {best.missing.slice(0, 6).map(item => item.name).join(' · ')}</div>}<div className="action-row"><button className="primary" onClick={() => setRecipe(best)}>View recipe</button><button className={`favorite-action ${favoriteIds.has(best.idMeal) ? 'saved' : ''}`} onClick={() => toggleFavorite(best)}>{favoriteIds.has(best.idMeal) ? '♥ Saved' : '♡ Save meal'}</button>{best.missing.length > 0 && <button className="secondary" onClick={() => addMissing(best)}>🛒 Add shopping list</button>}</div></div><div className="price"><small>ESTIMATED SHOPPING</small><strong>Rs. {best.shoppingCost.toLocaleString()}</strong><span>for {people} people</span>{best.overBudget ? <b>Over budget</b> : <i>Within budget</i>}</div></article><div className="recipe-grid">{visibleMeals.map(meal => <article className="recipe-card" key={meal.idMeal} onClick={() => setRecipe(meal)}><div className="recipe-top"><img className="recipe-image" src={meal.strMealThumb} alt={meal.strMeal} loading="lazy" /><span className="score">{meal.score}%</span><button className={`card-favorite ${favoriteIds.has(meal.idMeal) ? 'saved' : ''}`} aria-label={favoriteIds.has(meal.idMeal) ? `Remove ${meal.strMeal} from saved meals` : `Save ${meal.strMeal}`} onClick={event => { event.stopPropagation(); toggleFavorite(meal) }}>{favoriteIds.has(meal.idMeal) ? '♥' : '♡'}</button></div><h3>{meal.strMeal}</h3><div className="recipe-meta">{meal.minutes} min · Shop Rs. {meal.shoppingCost.toLocaleString()} · {meal.ingredientScore}% ingredients</div><div className="missing-list">{meal.missing.length ? `Buy: ${meal.missing.slice(0, 3).map(item => item.name).join(', ')}` : '✓ You have the key ingredients.'}</div></article>)}</div>{(canShowMore || visibleCount > 6) && <div className="results-pagination"><div className="results-pagination-copy"><strong>{Math.min(visibleCount, results.length - 1)} of {Math.max(0, results.length - 1)} meals</strong><span>{canShowMore ? 'Keep exploring more matches' : 'You’ve reached the end of the current matches'}</span></div><div className="results-pagination-actions">{canShowMore && <button className="show-more-button" onClick={() => setVisibleCount(value => Math.min(value + 6, results.length - 1))}>Show more meals <span>↓</span></button>}{visibleCount > 6 && <button className="show-less-button" onClick={() => setVisibleCount(6)}>Show fewer <span>↑</span></button>}</div></div>}</>}
    </section>
    <footer>CookTonight · Recipe data by TheMealDB · Nutrition estimates by Open Food Facts · Prices shown are planning estimates.</footer>
    {surpriseOpen && surpriseMeal && <div className="modal-backdrop" role="dialog" aria-modal="true" onClick={() => setSurpriseOpen(false)}><article className="surprise-modal" onClick={event => event.stopPropagation()} style={{ maxWidth: 760, width: 'calc(100% - 32px)', background: '#fff', borderRadius: 28, overflow: 'hidden', boxShadow: '0 30px 90px rgba(0,0,0,.22)' }}><div style={{ position: 'relative' }}><img src={surpriseMeal.strMealThumb} alt={surpriseMeal.strMeal} style={{ width: '100%', height: 300, objectFit: 'cover', display: 'block' }} /><button className="close" onClick={() => setSurpriseOpen(false)}>×</button></div><div style={{ padding: 32 }}><span className="eyebrow">YOUR MATCH · RANDOMLY PICKED</span><h2 style={{ margin: '8px 0 10px' }}>{surpriseMeal.strMeal}</h2><p style={{ margin: '0 0 18px', color: '#666' }}>{surpriseMeal.strArea || 'International'} cuisine · {surpriseMeal.minutes} min · {surpriseMeal.score}% match</p><div className="ingredient-row">{surpriseMeal.matched.slice(0, 7).map(item => <span className="have" key={`${item.name}-${item.measure}`}>✓ {item.name}</span>)}</div>{surpriseMeal.missing.length > 0 && <div className="missing">Need to buy: {surpriseMeal.missing.slice(0, 6).map(item => item.name).join(' · ')}</div>}<div className="action-row" style={{ marginTop: 22 }}><button className="primary" onClick={() => { setSurpriseOpen(false); setRecipe(surpriseMeal) }}>Cook this meal</button><button className="secondary" onClick={surprise}>🎲 Try another</button><button className={`favorite-action ${favoriteIds.has(surpriseMeal.idMeal) ? 'saved' : ''}`} onClick={() => toggleFavorite(surpriseMeal)}>{favoriteIds.has(surpriseMeal.idMeal) ? '♥ Saved' : '♡ Save meal'}</button></div></div></article></div>}
    {favoritesOpen && <div className="modal-backdrop" role="dialog" aria-modal="true" onClick={() => setFavoritesOpen(false)}><article className="favorites-modal" onClick={event => event.stopPropagation()}><div className="favorites-header"><div><span className="eyebrow">YOUR COLLECTION</span><h2>Saved meals</h2><p>{favorites.length ? `${favorites.length} meal${favorites.length === 1 ? '' : 's'} saved for later.` : 'Save recipes you want to try.'}</p></div><button className="close" onClick={() => setFavoritesOpen(false)}>×</button></div>{favorites.length ? <div className="saved-grid">{favoriteMeals.map(meal => <article className="saved-card" key={meal.idMeal} onClick={() => openFavorite(meal)}><img src={meal.strMealThumb} alt={meal.strMeal} /><div><h3>{meal.strMeal}</h3><span>{meal.strArea || 'International'} · {meal.minutes} min</span><button onClick={event => { event.stopPropagation(); toggleFavorite(meal) }}>Remove</button></div></article>)}</div> : <div className="empty-saved"><span>♡</span><h3>No saved meals yet</h3><p>Tap the heart on any meal you want to keep.</p></div>}</article></div>}
    {recipe && <div className="modal-backdrop" role="dialog" aria-modal="true" onClick={() => setRecipe(null)}><article className="modal" onClick={event => event.stopPropagation()}><button className="close" onClick={() => setRecipe(null)}>×</button><img src={recipe.strMealThumb} alt={recipe.strMeal} /><div className="modal-body"><div className="recipe-modal-top"><div><span className="eyebrow">{recipe.strCategory || 'RECIPE'}</span><h2>{recipe.strMeal}</h2></div><button className={`favorite-action ${favoriteIds.has(recipe.idMeal) ? 'saved' : ''}`} onClick={() => toggleFavorite(recipe)}>{favoriteIds.has(recipe.idMeal) ? '♥ Saved' : '♡ Save meal'}</button></div><p>{recipe.strArea || 'International'} cuisine · {recipe.minutes} min · estimated shopping Rs. {recipe.shoppingCost.toLocaleString()}</p><NutritionCard ingredients={recipe.items} servings={people} /><div style={{ marginTop: 28 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'end', gap: 16, marginBottom: 14 }}><div><span className="eyebrow">SMART ALTERNATIVES</span><h4 style={{ margin: '5px 0 0' }}>Want a different option?</h4></div><span style={{ color: '#777', fontSize: 13 }}>{alternativeMeals.length} options</span></div>{alternativeMeals.length > 0 && <div className="recipe-grid">{alternativeMeals.map(meal => <article className="recipe-card" key={`alt-${meal.idMeal}`} onClick={() => setRecipe(meal)}><div className="recipe-top"><img className="recipe-image" src={meal.strMealThumb} alt={meal.strMeal} loading="lazy" /><span className="score">{meal.alternativeType}</span><button className={`card-favorite ${favoriteIds.has(meal.idMeal) ? 'saved' : ''}`} aria-label={favoriteIds.has(meal.idMeal) ? `Remove ${meal.strMeal} from saved meals` : `Save ${meal.strMeal}`} onClick={event => { event.stopPropagation(); toggleFavorite(meal) }}>{favoriteIds.has(meal.idMeal) ? '♥' : '♡'}</button></div><h3>{meal.strMeal}</h3><div className="recipe-meta">{meal.minutes} min · Shop Rs. {meal.shoppingCost.toLocaleString()} · {meal.ingredientScore}% ingredients</div><div className="missing-list">{meal.alternativeType === 'Cheaper' ? `Save vs current: Rs. ${Math.max(0, recipe.shoppingCost - meal.shoppingCost).toLocaleString()}` : meal.alternativeType === 'Faster' ? `Save time: ${Math.max(0, recipe.minutes - meal.minutes)} min` : meal.alternativeType === 'Better match' ? `More of your ingredients: +${Math.max(0, meal.ingredientScore - recipe.ingredientScore)}%` : meal.missing.length ? `Buy: ${meal.missing.slice(0, 3).map(item => item.name).join(', ')}` : '✓ You have the key ingredients.'}</div></article>)}</div>}</div>
<h4>Ingredients</h4><div className="modal-ingredients">{recipe.items.map(item => <span key={`${item.name}-${item.measure}`}>{item.measure ? `${item.measure} ` : ''}{item.name}{recipe.matched.some(match => match.name === item.name) ? ' ✓' : ''}</span>)}</div><h4>Instructions</h4><div className="instructions">{recipe.steps.length ? recipe.steps.map((step, index) => <p key={index}><strong>{index + 1}.</strong> {step}</p>) : <p>No instructions supplied.</p>}</div></div></article></div>}
    {shoppingOpen && <ShoppingAssistant items={shoppingItems} onToggle={id => setShoppingItems(current => current.map(item => item.id === id ? { ...item, purchased: !item.purchased } : item))} onRemove={id => setShoppingItems(current => current.filter(item => item.id !== id))} onClearPurchased={() => setShoppingItems(current => current.filter(item => !item.purchased))} onClose={() => setShoppingOpen(false)} />}
  </main>
}
export default App
