import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const API = 'https://www.themealdb.com/api/json/v1/1'
const aliases = { tomatoes: 'tomato', potatoes: 'potato', onions: 'onion', chillies: 'chili', chilies: 'chili', chilli: 'chili', 'green chilli': 'green chili', 'green chilies': 'green chili', aloo: 'potato', tamatar: 'tomato', pyaaz: 'onion', pyaz: 'onion', dahi: 'yogurt', adrak: 'ginger', lehsan: 'garlic', 'adrak lehsan': 'ginger garlic' }
const ingredientGroups = { chicken: ['chicken', 'chicken breast', 'chicken thigh', 'chicken wings', 'chicken stock'], rice: ['rice', 'brown rice', 'basmati rice'], potato: ['potato', 'potatoes', 'sweet potato'], onion: ['onion', 'red onion', 'shallot'], tomato: ['tomato', 'tomatoes', 'tomato paste', 'canned tomatoes'], garlic: ['garlic', 'minced garlic', 'garlic paste'], ginger: ['ginger', 'ground ginger', 'ginger paste'], yogurt: ['yogurt', 'greek yogurt', 'curd'], chili: ['chili', 'chilli', 'green chili', 'red chili'], egg: ['egg', 'eggs'], milk: ['milk'], flour: ['flour', 'plain flour', 'all purpose flour'], lentil: ['lentil', 'lentils', 'dal'] }
const pantry = ['Chicken', 'Rice', 'Potatoes', 'Onion', 'Tomatoes', 'Eggs', 'Milk', 'Bread', 'Flour', 'Lentils', 'Garlic', 'Ginger', 'Yogurt', 'Green Chili']
const priceGuide = { chicken: 520, rice: 260, potato: 100, onion: 90, tomato: 120, yogurt: 180, ginger: 70, garlic: 80, chili: 70, spice: 120, flour: 140, egg: 90, milk: 220, bread: 160, lentil: 280 }
const substitutions = { yogurt: ['milk + lemon', 'cream', 'buttermilk'], ginger: ['ginger paste', 'a little garlic'], garlic: ['garlic paste', 'shallot'], tomato: ['canned tomato', 'tomato paste'], onion: ['shallot', 'red onion'], chicken: ['chickpeas', 'lentils', 'eggs'], rice: ['bulgur', 'couscous', 'potato'] }
const meatKeywords = ['chicken', 'beef', 'pork', 'lamb', 'mutton', 'goat', 'turkey', 'duck', 'ham', 'bacon', 'sausage', 'fish', 'salmon', 'tuna', 'prawn', 'shrimp', 'anchovy', 'sardine', 'crab', 'lobster', 'meat']
const normalize = value => { const cleaned = String(value || '').toLowerCase().trim().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' '); if (!cleaned) return ''; if (aliases[cleaned]) return aliases[cleaned]; return cleaned.replace(/s$/, '') }
const canonical = value => { const normalized = normalize(value); for (const [key, values] of Object.entries(ingredientGroups)) if (values.some(value => normalize(value) === normalized || normalized.includes(normalize(value)) || normalize(value).includes(normalized))) return key; return normalized }
const getIngredients = meal => Array.from({ length: 20 }, (_, index) => { const ingredient = meal[`strIngredient${index + 1}`]; const measure = meal[`strMeasure${index + 1}`]; if (!ingredient || !ingredient.trim()) return null; return { name: ingredient.trim(), normalized: normalize(ingredient), canonical: canonical(ingredient), measure: (measure || '').trim() } }).filter(Boolean)
const getSteps = text => String(text || '').replace(/\r/g, '').split(/\n+/).map(item => item.trim()).filter(Boolean).flatMap(item => item.split(/(?=\b(?:step|then|next|meanwhile|after)\s*\d*[:.)-])/i).map(step => step.trim()).filter(Boolean))
const estimateCost = (meal, people) => { const ingredients = getIngredients(meal); const raw = ingredients.reduce((total, ingredient) => total + (priceGuide[ingredient.canonical] || (ingredient.canonical.includes('spice') ? 120 : 95)), 0); return Math.max(350, Math.round(raw * Math.max(1, people / 4))) }
const scoreRecipe = (meal, availableIngredients, budget, people) => { const available = availableIngredients.map(canonical); const recipeIngredients = getIngredients(meal); const matched = recipeIngredients.filter(item => available.includes(item.canonical)); const missing = recipeIngredients.filter(item => !available.includes(item.canonical)); const uniqueRecipe = [...new Set(recipeIngredients.map(item => item.canonical))]; const uniqueMatched = [...new Set(matched.map(item => item.canonical))]; const ingredientMatch = uniqueRecipe.length ? uniqueMatched.length / uniqueRecipe.length : 0; const estimatedCost = estimateCost(meal, people); const budgetScore = budget >= estimatedCost ? 1 : Math.max(0, budget / Math.max(1, estimatedCost)); const missingPenalty = Math.min(0.25, missing.length * 0.025); const match = Math.max(0, Math.round((ingredientMatch * 0.72 + budgetScore * 0.28 - missingPenalty) * 100)); const text = `${meal.strMeal} ${meal.strCategory || ''} ${meal.strTags || ''} ${recipeIngredients.map(item => item.name).join(' ')}`.toLowerCase(); const vegetarian = !meatKeywords.some(keyword => text.includes(keyword)); const steps = getSteps(meal.strInstructions); const quick = steps.length <= 6 && meal.strInstructions.length < 900; return { ...meal, recipeIngredients, matched, missing, match, ingredientMatch: Math.round(ingredientMatch * 100), estimatedCost, overBudget: estimatedCost > budget, vegetarian, quick, steps } }
async function fetchMeals(ingredients) { const candidates = new Map(); for (const ingredient of ingredients.slice(0, 6)) { const query = normalize(ingredient).replace(/ /g, '_'); const response = await fetch(`${API}/filter.php?i=${encodeURIComponent(query)}`); if (!response.ok) continue; const data = await response.json(); (data.meals || []).slice(0, 12).forEach(meal => candidates.set(meal.idMeal, meal)) } const details = await Promise.all(Array.from(candidates.values()).slice(0, 30).map(async meal => { const response = await fetch(`${API}/lookup.php?i=${meal.idMeal}`); if (!response.ok) return null; const data = await response.json(); return data.meals?.[0] || null })); return details.filter(Boolean) }

function App() {
  const [people, setPeople] = useState(4), [budget, setBudget] = useState(2000), [ingredients, setIngredients] = useState(['Chicken', 'Rice', 'Potatoes', 'Onion', 'Tomatoes']), [ingredientInput, setIngredientInput] = useState(''), [meals, setMeals] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [selectedMeal, setSelectedMeal] = useState(null), [budgetOnly, setBudgetOnly] = useState(false), [language, setLanguage] = useState('en'), [diet, setDiet] = useState('any'), [cooking, setCooking] = useState(false), [step, setStep] = useState(0)
  useEffect(() => { let active = true; setLoading(true); setError(''); fetchMeals(ingredients).then(data => { if (!active) return; setMeals(data); setLoading(false); if (!data.length) setError('No meals matched those ingredients. Try chicken, rice, potato or onion.') }).catch(() => { if (!active) return; setError('Recipe service is temporarily unavailable. Please try again.'); setLoading(false) }); return () => { active = false } }, [ingredients])
  const results = useMemo(() => meals.map(meal => scoreRecipe(meal, ingredients, budget, people)).filter(meal => (diet === 'any' || (diet === 'vegetarian' && meal.vegetarian) || (diet === 'quick' && meal.quick)) && (!budgetOnly || !meal.overBudget)).sort((a, b) => b.match - a.match), [meals, ingredients, budget, people, budgetOnly, diet])
  const best = results[0], suggested = pantry.filter(item => !ingredients.some(existing => canonical(existing) === canonical(item))).slice(0, 6), missingSubstitutions = best?.missing.filter(item => substitutions[item.canonical]).slice(0, 3) || [], shoppingEstimate = best ? Math.max(0, best.estimatedCost - best.matched.reduce((total, item) => total + (priceGuide[item.canonical] || 95), 0)) : 0, budgetPercent = best ? Math.min(100, Math.round((best.estimatedCost / Math.max(1, budget)) * 100)) : 0
  const addIngredient = value => { const clean = value.trim(); if (!clean || ingredients.some(item => canonical(item) === canonical(clean))) return; setIngredients([...ingredients, clean]); setIngredientInput('') }
  const startCooking = meal => { setSelectedMeal(meal); setCooking(true); setStep(0) }

  return <main className="app">
    <nav className="nav"><div className="brand"><span>🍳</span> CookTonight</div><div className="nav-actions"><button className="language" onClick={() => setLanguage(language === 'en' ? 'ur' : 'en')}>{language === 'en' ? 'اردو' : 'English'}</button><div className="nav-link">Real meals · Your ingredients · Your budget</div></div></nav>
    <section className="hero"><div className="hero-copy"><div className="eyebrow">LESS THINKING · BETTER MEALS</div><h1>{language === 'en' ? <>What should I<br /><em>cook tonight?</em></> : <>آج رات<br /><em>کیا پکائیں؟</em></>}</h1><p>{language === 'en' ? "Tell us what is in your kitchen, how many people you're feeding and what you can spend. We'll find practical meals you can actually make." : 'اپنے پاس موجود چیزیں، افراد اور بجٹ بتائیں۔ ہم آپ کے لیے آسان اور مناسب کھانے تلاش کریں گے۔'}</p></div><div className="pan">🍳</div></section>
    <section className="planner"><div className="input-card"><label>PEOPLE</label><div className="number-input"><button onClick={() => setPeople(Math.max(1, people - 1))}>−</button><strong>{people}</strong><button onClick={() => setPeople(people + 1)}>+</button></div></div><div className="input-card budget-card"><label>TONIGHT'S BUDGET</label><div className="budget-input"><span>Rs.</span><input type="number" value={budget} onChange={e => setBudget(Math.max(0, Number(e.target.value)))} /></div></div><div className="input-card ingredients-card"><label>WHAT DO YOU HAVE?</label><div className="chips">{ingredients.map(item => <button className="chip" key={item} onClick={() => setIngredients(ingredients.filter(x => x !== item))}>{item} <span>×</span></button>)}<input value={ingredientInput} onChange={e => setIngredientInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && addIngredient(ingredientInput)} placeholder="Add ingredient..." /></div><div className="quick-add">{suggested.map(item => <button key={item} onClick={() => addIngredient(item)}>+ {item}</button>)}</div></div></section>
    <section className="filters"><span>FILTERS</span><button className={diet === 'any' ? 'active' : ''} onClick={() => setDiet('any')}>All meals</button><button className={diet === 'vegetarian' ? 'active' : ''} onClick={() => setDiet('vegetarian')}>Vegetarian</button><button className={diet === 'quick' ? 'active' : ''} onClick={() => setDiet('quick')}>Quick picks</button></section>
    <section className="results"><div className="section-heading"><div><span className="eyebrow">SMART MATCHING</span><h2>Meals that make sense</h2></div><label className="toggle"><input type="checkbox" checked={budgetOnly} onChange={e => setBudgetOnly(e.target.checked)} /><span>Only show within budget</span></label></div>
      {loading && <div className="loading-card"><div className="loader" />Finding meals and comparing your ingredients…</div>}{!loading && error && <div className="error-card">{error}</div>}{!loading && !error && !best && <div className="error-card">Nothing fits these filters. Try increasing the budget, changing the diet filter, or turn off “Only show within budget”.</div>}
      {!loading && best && <><div className="best-card"><div className="dish-image"><img src={best.strMealThumb} alt={best.strMeal} /></div><div className="best-info"><div className="match">{best.match}% OVERALL MATCH · {best.ingredientMatch}% INGREDIENT MATCH</div><h3>{best.strMeal}</h3><p>{best.strArea || 'International'} · for {people} people · based on your pantry</p><div className="ingredient-row">{best.matched.slice(0, 8).map(item => <span className="have" key={item.canonical}>✓ {item.name}</span>)}</div>{best.missing.length > 0 && <div className="missing">Shopping list: {best.missing.slice(0, 6).map(item => `${item.measure ? `${item.measure} ` : ''}${item.name}`).join(' · ')}</div>}<div className="action-row"><button className="primary" onClick={() => setSelectedMeal(best)}>View recipe</button><button className="cook-button" onClick={() => startCooking(best)}>▶ Start cooking</button></div></div><div className="price"><small>PLANNING ESTIMATE</small><strong>Rs. {best.estimatedCost.toLocaleString()}</strong><span>~ Rs. {Math.ceil(best.estimatedCost / people)} / person</span>{best.overBudget ? <b>Over budget</b> : <i>Within your budget</i>}</div></div>
      <div className="budget-meter"><div><strong>Budget fit</strong><span>Rs. {best.estimatedCost.toLocaleString()} of Rs. {budget.toLocaleString()}</span></div><div className="meter"><span style={{ width: `${budgetPercent}%` }} /></div></div>
      <div className="insight"><span>🛒</span><div><strong>What you'll likely need to buy</strong><p>{best.missing.length ? `${best.missing.slice(0, 5).map(item => `${item.measure ? `${item.measure} ` : ''}${item.name}`).join(', ')}${best.missing.length > 5 ? ' and more' : ''}` : 'Nothing — you have the key ingredients.'}</p></div><strong>~ Rs. {shoppingEstimate.toLocaleString()}</strong></div>
      {missingSubstitutions.length > 0 && <div className="substitution"><div><strong>💡 Missing something?</strong><p>We found simple swaps for ingredients you may not have.</p></div><div className="swap-list">{missingSubstitutions.map(item => <span key={item.canonical}>No {item.name} → {substitutions[item.canonical][0]}</span>)}</div></div>}
      <div className="recipe-grid">{results.slice(1, 7).map(recipe => <article className="recipe-card" key={recipe.idMeal} onClick={() => setSelectedMeal(recipe)}><div className="recipe-top"><img className="recipe-image" src={recipe.strMealThumb} alt={recipe.strMeal} /><span className="score">{recipe.match}% match</span></div><h3>{recipe.strMeal}</h3><div className="recipe-meta"><span>Rs. {recipe.estimatedCost.toLocaleString()}</span><span>·</span><span>{recipe.ingredientMatch}% ingredients</span></div><div className="missing-list">{recipe.missing.length ? `Buy: ${recipe.missing.slice(0, 3).map(item => item.name).join(', ')}` : 'You have the key ingredients!'}</div></article>)}</div></>}
    </section><footer>CookTonight · Recipe data by TheMealDB · Prices are planning estimates, not live store prices.</footer>
    {selectedMeal && !cooking && <div className="modal-backdrop" onClick={() => setSelectedMeal(null)}><article className="modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setSelectedMeal(null)}>×</button><img src={selectedMeal.strMealThumb} alt={selectedMeal.strMeal} /><div className="modal-body"><span className="eyebrow">{selectedMeal.strCategory || 'RECIPE'}</span><h2>{selectedMeal.strMeal}</h2><p>{selectedMeal.strArea || 'International'} cuisine · estimated total Rs. {selectedMeal.estimatedCost.toLocaleString()}</p><div className="action-row"><button className="primary" onClick={() => startCooking(selectedMeal)}>▶ Start cooking</button></div><h4>Your shopping list</h4><div className="shopping-list">{selectedMeal.missing.map(item => <span key={item.canonical}>🛒 {item.measure ? `${item.measure} ` : ''}{item.name}{substitutions[item.canonical] ? ` · swap: ${substitutions[item.canonical][0]}` : ''}</span>)}{!selectedMeal.missing.length && <span>✓ You already have the key ingredients.</span>}</div><h4>Ingredients</h4><div className="modal-ingredients">{selectedMeal.recipeIngredients.map(item => <span key={`${item.name}-${item.measure}`}>{selectedMeal.matched.some(match => match.canonical === item.canonical) ? '✓ ' : ''}{item.measure ? `${item.measure} ` : ''}{item.name}</span>)}</div>{selectedMeal.strInstructions && <><h4>How to make it</h4><p className="instructions">{selectedMeal.strInstructions}</p></>}</div></article></div>}
    {selectedMeal && cooking && <div className="modal-backdrop"><article className="cook-mode" onClick={e => e.stopPropagation()}><div className="cook-head"><div><span className="eyebrow">COOK MODE</span><h2>{selectedMeal.strMeal}</h2></div><button className="close" onClick={() => { setCooking(false); setSelectedMeal(null) }}>×</button></div><img src={selectedMeal.strMealThumb} alt={selectedMeal.strMeal} /><div className="cook-progress"><span>Step {Math.min(step + 1, Math.max(1, selectedMeal.steps.length))} of {Math.max(1, selectedMeal.steps.length)}</span><div className="meter"><span style={{ width: `${selectedMeal.steps.length ? ((step + 1) / selectedMeal.steps.length) * 100 : 100}%` }} /></div></div><div className="step-card"><div className="step-number">{step + 1}</div><p>{selectedMeal.steps[step] || selectedMeal.strInstructions || 'Prepare your ingredients and enjoy your meal.'}</p></div><div className="cook-actions"><button className="secondary" disabled={step === 0} onClick={() => setStep(Math.max(0, step - 1))}>← Previous</button>{step < selectedMeal.steps.length - 1 ? <button className="primary" onClick={() => setStep(step + 1)}>Next step →</button> : <button className="primary" onClick={() => { setCooking(false); setSelectedMeal(null) }}>✓ Done cooking</button>}</div></article></div>}
  </main>
}

createRoot(document.getElementById('root')).render(<App />)
