import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const API = 'https://www.themealdb.com/api/json/v1/1'
const aliases = { tomatoes: 'tomato', potatoes: 'potato', onions: 'onion', chillies: 'chili', chilies: 'chili', chilli: 'chili', 'green chilli': 'green chili', 'green chilies': 'green chili', aloo: 'potato', tamatar: 'tomato', pyaaz: 'onion', pyaz: 'onion', dahi: 'yogurt', adrak: 'ginger', lehsan: 'garlic' }
const groups = { chicken: ['chicken', 'chicken breast', 'chicken thigh', 'chicken wings'], rice: ['rice', 'basmati rice', 'brown rice'], potato: ['potato', 'sweet potato'], onion: ['onion', 'red onion', 'shallot'], tomato: ['tomato', 'tomato paste', 'canned tomato'], garlic: ['garlic', 'garlic paste', 'minced garlic'], ginger: ['ginger', 'ginger paste'], yogurt: ['yogurt', 'greek yogurt', 'curd'], chili: ['chili', 'green chili', 'red chili'], egg: ['egg', 'eggs'], milk: ['milk'], flour: ['flour', 'plain flour'], lentil: ['lentil', 'lentils', 'dal'] }
const pantry = ['Chicken', 'Rice', 'Potatoes', 'Onion', 'Tomatoes', 'Eggs', 'Milk', 'Bread', 'Flour', 'Lentils', 'Garlic', 'Ginger', 'Yogurt', 'Green Chili']
const prices = { chicken: 520, rice: 260, potato: 100, onion: 90, tomato: 120, garlic: 80, ginger: 70, yogurt: 180, chili: 70, egg: 90, milk: 220, flour: 140, lentil: 280, bread: 160 }
const meat = ['chicken', 'beef', 'pork', 'lamb', 'mutton', 'goat', 'turkey', 'duck', 'ham', 'bacon', 'sausage', 'fish', 'salmon', 'tuna', 'prawn', 'shrimp', 'anchovy', 'crab', 'lobster']
const normalize = value => { const text = String(value || '').toLowerCase().trim().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' '); return aliases[text] || text.replace(/s$/, '') }
const canonical = value => { const text = normalize(value); for (const [key, values] of Object.entries(groups)) if (values.some(item => normalize(item) === text || text.includes(normalize(item)) || normalize(item).includes(text))) return key; return text }
const ingredientsOf = meal => Array.from({ length: 20 }, (_, i) => ({ name: meal[`strIngredient${i + 1}`]?.trim(), measure: meal[`strMeasure${i + 1}`]?.trim() })).filter(item => item.name).map(item => ({ ...item, key: canonical(item.name) }))
const instructionsOf = text => { const value = String(text || '').replace(/\r/g, '').trim(); if (!value) return ['Follow the recipe instructions.']; const paragraphs = value.split(/\n+/).map(item => item.trim()).filter(Boolean); if (paragraphs.length > 1) return paragraphs; const numbered = value.split(/(?=\b(?:step\s*\d+|\d+\s*[.)-])\s*)/i).map(item => item.trim()).filter(Boolean); if (numbered.length > 1) return numbered; const sentences = value.split(/(?<=[.!?])\s+/).map(item => item.trim()).filter(Boolean); return sentences.length > 1 ? sentences : [value] }
const costOf = (meal, people) => Math.max(350, Math.round(ingredientsOf(meal).reduce((sum, item) => sum + (prices[item.key] || 95), 0) * Math.max(1, people / 4)))
const scoreOf = (meal, available, budget, people) => { const have = available.map(canonical); const items = ingredientsOf(meal); const unique = [...new Set(items.map(item => item.key))]; const matchedKeys = unique.filter(key => have.includes(key)); const matched = items.filter(item => have.includes(item.key)); const missing = items.filter(item => !have.includes(item.key)); const ingredientScore = unique.length ? matchedKeys.length / unique.length : 0; const cost = costOf(meal, people); const budgetScore = budget >= cost ? 1 : Math.max(0, budget / Math.max(cost, 1)); const score = Math.max(0, Math.min(100, Math.round(ingredientScore * 75 + budgetScore * 25))); const text = items.map(item => item.name).join(' ').toLowerCase(); return { ...meal, items, matched, missing, ingredientScore: Math.round(ingredientScore * 100), score, cost, overBudget: cost > budget, vegetarian: !meat.some(word => text.includes(word)), steps: instructionsOf(meal.strInstructions) } }
async function getMeals(ingredients) { const candidates = new Map(); for (const ingredient of ingredients.slice(0, 6)) { const response = await fetch(`${API}/filter.php?i=${encodeURIComponent(normalize(ingredient).replace(/ /g, '_'))}`); if (!response.ok) continue; const data = await response.json(); (data.meals || []).slice(0, 10).forEach(meal => candidates.set(meal.idMeal, meal)) } const details = await Promise.all([...candidates.values()].slice(0, 30).map(async meal => { const response = await fetch(`${API}/lookup.php?i=${meal.idMeal}`); if (!response.ok) return null; const data = await response.json(); return data.meals?.[0] || null })); return details.filter(Boolean) }

function App() {
  const [people, setPeople] = useState(4), [budget, setBudget] = useState(2000), [ingredients, setIngredients] = useState(['Chicken', 'Rice', 'Potatoes', 'Onion', 'Tomatoes']), [input, setInput] = useState(''), [meals, setMeals] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [filter, setFilter] = useState('all'), [budgetOnly, setBudgetOnly] = useState(false), [recipe, setRecipe] = useState(null), [cooking, setCooking] = useState(false), [step, setStep] = useState(0)
  useEffect(() => { let alive = true; setLoading(true); setError(''); getMeals(ingredients).then(data => { if (!alive) return; setMeals(data); setLoading(false); if (!data.length) setError('No recipes found for these ingredients.') }).catch(() => { if (!alive) return; setError('Unable to load recipes right now. Please try again.'); setLoading(false) }); return () => { alive = false } }, [ingredients])
  const results = useMemo(() => meals.map(meal => scoreOf(meal, ingredients, budget, people)).filter(meal => (filter === 'all' || (filter === 'vegetarian' && meal.vegetarian) || (filter === 'quick' && meal.steps.length <= 6)) && (!budgetOnly || !meal.overBudget)).sort((a, b) => b.score - a.score), [meals, ingredients, budget, people, filter, budgetOnly])
  const best = results[0]
  const suggested = pantry.filter(item => !ingredients.some(existing => canonical(existing) === canonical(item))).slice(0, 6)
  const add = value => { const clean = value.trim(); if (!clean || ingredients.some(item => canonical(item) === canonical(clean))) return; setIngredients(current => [...current, clean]); setInput('') }
  const openRecipe = meal => { setCooking(false); setStep(0); setRecipe(meal) }
  const startCooking = meal => { setRecipe(meal); setCooking(true); setStep(0) }
  const close = () => { setRecipe(null); setCooking(false); setStep(0) }

  return <main className="app">
    <nav className="nav"><div className="brand">🍳 CookTonight</div><div className="nav-link">Your ingredients · Your budget · Your meal</div></nav>
    <section className="hero"><div><span className="eyebrow">LESS THINKING · BETTER MEALS</span><h1>What should I<br /><em>cook tonight?</em></h1><p>Tell us what you have, how many people you're feeding and what you can spend. We'll find meals that make sense.</p></div><div className="pan">🍳</div></section>
    <section className="planner"><div className="input-card"><label>PEOPLE</label><div className="number-input"><button onClick={() => setPeople(value => Math.max(1, value - 1))}>−</button><strong>{people}</strong><button onClick={() => setPeople(value => value + 1)}>+</button></div></div><div className="input-card"><label>BUDGET</label><div className="budget-input"><span>Rs.</span><input type="number" min="0" value={budget} onChange={event => setBudget(Math.max(0, Number(event.target.value) || 0))} /></div></div><div className="input-card ingredients-card"><label>WHAT DO YOU HAVE?</label><div className="chips">{ingredients.map(item => <button className="chip" key={item} onClick={() => setIngredients(current => current.filter(value => value !== item))}>{item} ×</button>)}<input value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => event.key === 'Enter' && add(input)} placeholder="Add ingredient…" /></div><div className="quick-add">{suggested.map(item => <button key={item} onClick={() => add(item)}>+ {item}</button>)}</div></div></section>
    <section className="filters"><span>FILTERS</span><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>All meals</button><button className={filter === 'vegetarian' ? 'active' : ''} onClick={() => setFilter('vegetarian')}>Vegetarian</button><button className={filter === 'quick' ? 'active' : ''} onClick={() => setFilter('quick')}>Quick picks</button><label className="toggle"><input type="checkbox" checked={budgetOnly} onChange={event => setBudgetOnly(event.target.checked)} /> Within budget</label></section>
    <section className="results"><div className="section-heading"><div><span className="eyebrow">SMART MATCHING</span><h2>Meals that make sense</h2></div></div>
      {loading && <div className="loading-card"><div className="loader" />Finding meals…</div>}{!loading && error && <div className="error-card">{error}</div>}{!loading && !error && !best && <div className="error-card">Nothing matches those filters. Try a larger budget or another filter.</div>}
      {!loading && best && <><article className="best-card"><div className="dish-image"><img src={best.strMealThumb} alt={best.strMeal} /></div><div className="best-info"><span className="match">{best.score}% MATCH · {best.ingredientScore}% INGREDIENTS</span><h3>{best.strMeal}</h3><p>{best.strArea || 'International'} cuisine · planned for {people} people</p><div className="ingredient-row">{best.matched.slice(0, 7).map(item => <span className="have" key={`${item.name}-${item.measure}`}>✓ {item.name}</span>)}</div>{best.missing.length > 0 && <div className="missing">Need to buy: {best.missing.slice(0, 6).map(item => `${item.measure ? `${item.measure} ` : ''}${item.name}`).join(' · ')}</div>}<div className="action-row"><button className="primary" onClick={() => openRecipe(best)}>View recipe</button><button className="cook-button" onClick={() => startCooking(best)}>▶ Start cooking</button></div></div><div className="price"><small>ESTIMATED TOTAL</small><strong>Rs. {best.cost.toLocaleString()}</strong><span>~ Rs. {Math.ceil(best.cost / people)} / person</span>{best.overBudget ? <b>Over budget</b> : <i>Within budget</i>}</div></article><div className="budget-meter"><div><strong>Budget fit</strong><span>Rs. {best.cost.toLocaleString()} / Rs. {budget.toLocaleString()}</span></div><div className="meter"><span style={{ width: `${Math.min(100, Math.round(best.cost / Math.max(1, budget) * 100))}%` }} /></div></div><div className="recipe-grid">{results.slice(1, 7).map(meal => <article className="recipe-card" key={meal.idMeal} onClick={() => openRecipe(meal)}><div className="recipe-top"><img className="recipe-image" src={meal.strMealThumb} alt={meal.strMeal} /><span className="score">{meal.score}%</span></div><h3>{meal.strMeal}</h3><div className="recipe-meta">Rs. {meal.cost.toLocaleString()} · {meal.ingredientScore}% ingredients</div><div className="missing-list">{meal.missing.length ? `Buy: ${meal.missing.slice(0, 3).map(item => item.name).join(', ')}` : 'You have the key ingredients.'}</div></article>)}</div></>}
    </section><footer>CookTonight · Recipe data by TheMealDB · Prices shown are planning estimates.</footer>
    {recipe && <div className="modal-backdrop" role="dialog" aria-modal="true" onClick={close}>{cooking ? <article className="cook-mode" onClick={event => event.stopPropagation()}><button className="close" onClick={close} aria-label="Close">×</button><div className="cook-head"><div><span className="eyebrow">COOK MODE</span><h2>{recipe.strMeal}</h2></div></div><img src={recipe.strMealThumb} alt={recipe.strMeal} /><div className="cook-progress"><strong>Step {step + 1} of {recipe.steps.length}</strong><div className="meter"><span style={{ width: `${Math.round((step + 1) / recipe.steps.length * 100)}%` }} /></div></div><div className="step-card"><div className="step-number">{step + 1}</div><p>{recipe.steps[step]}</p></div><div className="cook-actions"><button className="secondary" disabled={step === 0} onClick={() => setStep(value => value - 1)}>← Previous</button>{step < recipe.steps.length - 1 ? <button className="primary" onClick={() => setStep(value => value + 1)}>Next step →</button> : <button className="primary" onClick={close}>✓ Done cooking</button>}</div></article> : <article className="modal" onClick={event => event.stopPropagation()}><button className="close" onClick={close} aria-label="Close">×</button><img src={recipe.strMealThumb} alt={recipe.strMeal} /><div className="modal-body"><span className="eyebrow">{recipe.strCategory || 'RECIPE'}</span><h2>{recipe.strMeal}</h2><p>{recipe.strArea || 'International'} cuisine · estimated total Rs. {recipe.cost.toLocaleString()}</p><div className="action-row"><button className="primary" onClick={() => startCooking(recipe)}>▶ Start cooking</button></div><h4>Ingredients</h4><div className="modal-ingredients">{recipe.items.map(item => <span key={`${item.name}-${item.measure}`}>{item.measure ? `${item.measure} ` : ''}{item.name}{recipe.matched.some(match => match.name === item.name) ? ' ✓' : ''}</span>)}</div><h4>What you need to buy</h4><div className="shopping-list">{recipe.missing.length ? recipe.missing.map(item => <span key={`${item.name}-${item.measure}`}>🛒 {item.measure ? `${item.measure} ` : ''}{item.name}</span>) : <span>✓ Nothing essential missing</span>}</div><h4>Instructions</h4><p className="instructions">{recipe.strInstructions}</p></div></article>}</div>}
  </main>
}

createRoot(document.getElementById('root')).render(<App />)
