const API = 'https://www.themealdb.com/api/json/v1/1'
const state = { loaded: false, meals: [], visible: 6, loading: false }
const normalize = value => String(value || '').toLowerCase().trim().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').replace(/s$/, '')
const ingredients = meal => Array.from({ length: 20 }, (_, i) => meal[`strIngredient${i + 1}`]?.trim()).filter(Boolean)
const currentIngredients = () => [...document.querySelectorAll('.chip')].map(node => node.textContent.replace(/\s*×\s*$/, '').trim()).filter(Boolean)
const score = (meal, have) => { const items = ingredients(meal); const owned = items.filter(item => have.some(value => normalize(value) === normalize(item) || normalize(value).includes(normalize(item)) || normalize(item).includes(normalize(value)))); return items.length ? Math.round(owned.length / items.length * 100) : 0 }
const style = () => { if (document.getElementById('professional-browse-style')) return; const node = document.createElement('style'); node.id = 'professional-browse-style'; node.textContent = '.browse-more-wrap{display:flex;flex-direction:column;align-items:center;gap:8px;margin:28px 0 8px}.browse-more{border:1px solid rgba(20,20,20,.12);background:#fff;border-radius:999px;padding:13px 24px;font-weight:700;cursor:pointer;box-shadow:0 8px 24px rgba(0,0,0,.06)}.browse-more:hover{transform:translateY(-1px);box-shadow:0 12px 28px rgba(0,0,0,.1)}.browse-count{font-size:13px;color:#777}.browse-extra-card{overflow:hidden}.browse-extra-card .recipe-card-body{padding:16px}.browse-extra-card .recipe-card-tags{display:flex;gap:6px;font-size:11px;color:#777;text-transform:uppercase}.browse-extra-card .card-action{margin-top:12px}.browse-extra-card{cursor:pointer}.browse-modal{position:fixed;inset:0;background:rgba(0,0,0,.58);z-index:10000;display:flex;align-items:center;justify-content:center;padding:20px}.browse-modal-inner{background:#fff;border-radius:24px;max-width:760px;width:100%;max-height:90vh;overflow:auto;position:relative}.browse-modal-inner img{width:100%;max-height:360px;object-fit:cover}.browse-modal-content{padding:24px}.browse-modal-close{position:absolute;right:16px;top:16px;width:40px;height:40px;border:0;border-radius:50%;background:#fff;font-size:24px;cursor:pointer}.browse-modal-content h2{margin:6px 0 8px}.browse-modal-content .browse-modal-meta{color:#666;margin-bottom:20px}.browse-modal-content h4{margin:20px 0 10px}.browse-modal-content li{margin:6px 0}.browse-modal-loading{padding:40px;text-align:center}'; document.head.appendChild(node) }
const openModal = meal => { const modal = document.createElement('div'); modal.className = 'browse-modal'; modal.innerHTML = `<div class="browse-modal-inner"><button class="browse-modal-close" aria-label="Close">×</button><img src="${meal.strMealThumb}" alt="${meal.strMeal}"><div class="browse-modal-content"><span class="eyebrow">${meal.strCategory || 'RECIPE'}</span><h2>${meal.strMeal}</h2><div class="browse-modal-meta">${meal.strArea || 'International'} cuisine · ${score(meal, currentIngredients())}% ingredient match</div><h4>Ingredients</h4><ul>${ingredients(meal).map(item => `<li>${item}</li>`).join('')}</ul><h4>Instructions</h4><p>${String(meal.strInstructions || 'No instructions supplied.').replace(/\r\n?/g, '<br><br>')}</p></div></div>`; modal.querySelector('.browse-modal-close').onclick = () => modal.remove(); modal.onclick = event => { if (event.target === modal) modal.remove() }; document.body.appendChild(modal) }
const render = () => { const grid = document.querySelector('.recipe-grid'); if (!grid) return; let wrap = document.querySelector('.browse-more-wrap'); if (!wrap) { wrap = document.createElement('div'); wrap.className = 'browse-more-wrap'; grid.after(wrap) } wrap.innerHTML = ''; const remaining = state.meals.length - state.visible; if (remaining > 0) { const button = document.createElement('button'); button.className = 'browse-more'; button.textContent = `Show more meals ↓`; button.onclick = () => { state.visible += 6; render() }; const count = document.createElement('small'); count.className = 'browse-count'; count.textContent = `Showing ${Math.min(state.visible, state.meals.length)} of ${state.meals.length} additional matches`; wrap.append(button, count) } else if (state.meals.length > 6) { const button = document.createElement('button'); button.className = 'browse-more'; button.textContent = 'Show fewer meals ↑'; button.onclick = () => { state.visible = 6; render() }; wrap.append(button) } }
const load = async () => { if (state.loading) return; const have = currentIngredients(); if (!have.length) return; state.loading = true; try { const ids = new Set(); for (const item of have.slice(0, 6)) { const response = await fetch(`${API}/filter.php?i=${encodeURIComponent(normalize(item).replace(/ /g, '_'))}`); const data = await response.json(); (data.meals || []).forEach(meal => ids.add(meal.idMeal)) } const details = await Promise.all([...ids].slice(0, 60).map(async id => { const response = await fetch(`${API}/lookup.php?i=${id}`); const data = await response.json(); return data.meals?.[0] || null })); const existing = new Set([...document.querySelectorAll('.recipe-card h3')].map(node => node.textContent.trim())); state.meals = details.filter(Boolean).filter(meal => !existing.has(meal.strMeal)).sort((a, b) => score(b, have) - score(a, have)); state.visible = 6; state.loaded = true; render() } catch {} finally { state.loading = false } }
const observe = () => { style(); const observer = new MutationObserver(() => { const grid = document.querySelector('.recipe-grid'); if (grid && !state.loaded && !state.loading) load(); }); observer.observe(document.body, { childList: true, subtree: true }); setTimeout(load, 1800) }
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', observe); else observe()
